### ISSUE TITLE
[Feature Request] Add double page support for windows and linux version

### ISSUE THREAD

**Issue by PDJLR** [Suwayomi/Tachidesk-JUI#75] opened 2023-02-16 10:39 UTC
### **Suggestions**
---------------------------------------------------------
- Add double page support like tachidesk-server, that type of reading, add it on windows and linux versions, android with big screens too.

**Comment by Syer10** [comment] 2023-02-16 15:12
Duplicate of https://github.com/Suwayomi/Tachidesk-JUI/issues/33

**Closed by Syer10** 2023-02-16 15:12 UTC
Labels: enhancement
