### ISSUE TITLE
[Bug] Color picker not functioning as intended (visually for the most part)

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/Tachidesk-JUI#18] opened 2021-08-19 17:40 UTC
## Steps to reproduce
1. Choosing primary or secondary from Appearance menu.

### Expected behavior
1. The tickmark should change to different option when clicked.
![image](https://user-images.githubusercontent.com/82655889/130115256-a154e23c-49e3-4802-8269-dc2b63989d4c.png)

### Actual behavior
1. Both the sections in the above window stay the same when clicked but works as intended in the background. The bottom section should include a tick mark as well.

2. Right side of the custom color picker is not displaying properly. I think the selecting the element is glitched? 
Im guessing splitting the right side to elements to select from failed . Now, each element now displays the whole range of colors rather than small part of them to choose from.
![image](https://user-images.githubusercontent.com/82655889/130116125-1b1772bd-9c45-43ff-951e-01ca01acb96f.png)

**Comment by BaccanoMob** [comment] 2021-08-19 17:47
small update on the first issue here,
The tick does not change no matter what if the first click or color choosing happens in the above section. It only works perfectly once there is click in the bottom section but not until then.

**Comment by Syer10** [comment] 2021-08-19 17:49
Found the cause of the first issue, its fixed, second is more difficult since its Tachiyomi 1.x code

**Comment by BaccanoMob** [comment] 2021-08-20 19:46
For the second, i rewrote from the code of yours. Though I changed the layouts partly for my needs, it functions properly as seen below.
![image](https://user-images.githubusercontent.com/82655889/130284794-631853ee-bc32-4373-b705-2a1dbe379816.png)
I can share the code i wrote later once I clean it up a bit.

**Comment by Syer10** [comment] 2021-08-20 19:58
Awesome, thanks for the help 💯

**Comment by Syer10** [comment] 2021-08-20 20:45
Fixed by https://github.com/Suwayomi/Tachidesk-JUI/commit/6ca93350d5de97c181d37edb6764521cde79c8ca and https://github.com/Suwayomi/Tachidesk-JUI/commit/95fb8d6eae255be7d7385a4a6457108ba16db5a0
Thanks for the fix!

**Closed by Syer10** 2021-08-20 20:45 UTC
Labels: bug

**Comment by Syer10** [comment] 2022-02-27 21:50
Fixed another bug that I found a while ago that relates to this in https://github.com/Suwayomi/Tachidesk-JUI/commit/03ef9019ae566b7680e51d5a1a2ce497d78f9cdd
